In [2]:
import torch

# basis
x = torch.arange(12)  # create vector/tensor, int and computed by CPU by default.
print(x)
print(x.shape)        # (member)access tensor's shape, length of every axis precisly.
print(x.numel())      # (method)access tensor's size, typically (shape.x) x (shape.y)
X = x.reshape(3, 4)   # (method)change shape of tensor by reshape. 
                      # reshape(row, column), if we use -1 in one of the parameter,
                      # it will be autoly calculate, like: 3,-1 -> 3,4
print(X)
X = x.reshape(-1, 3)
print(X)              # (member)
print(torch.zeros((2, 3, 4)))   # (method)create a all 0s tensor, 
                                # shape(number, row, column)
print(torch.ones((2, 3, 4)))    # (method)create a all 1s tensor, 
                                # shape(number, row, column)
print(torch.randn(3, 4))        # (method)create a random tensor, 
                                # samples from nornal distribution
                                # (mean value 0 and standard deviation 1)
print(torch.tensor(data=[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]))  # (method)create tensor by list or nested list

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[-0.9683, -0.6123, -0.2338,  1.2812],
        [ 0.5319, -0.9856,  1.5268, -0.6371],
        [-0.5718, -1.5071,  0.0575, -0.3224]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In [15]:
# operation

# for same shape, operation will execute on every pair of tensor
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
X = torch.arange(12).reshape((3, 4))
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# basic operations
# these operations are operated on correlated elements, like (a1 */+- b1, a2 */+- b2)
print('basic operations:')
print(x+y)
print(x-y)
print(x*y)  # Hadamard production. correlated element production, not dot production.
print(x/y)  # 
print(x**y)
print(X==Y)
print(X>Y)
print(X<Y)

# torch function receiving 1 or 2 parameters
print('\ntorch function for maths: ')
print(torch.exp(x))
print(torch.cat((X, Y), dim=0))  # dimension 0: vertical concatenate
print(torch.cat((X, Y), dim=1))  # dimension 1: horizontal concatenate
print(X.sum())
print(X.sum(axis=0))  # aggregate rows
print(X.sum(axis=1))  # aggregate columns
print(X.sum(axis=1, keepdims=True))  # usually keep dimensions for columns aggregation
print(X.cumsum(axis=1))     # aggregate rows/columns and keep result in every row/column, keep dimension

# production
print('\nproduction: ')
print(X.mv(y))                  # matrix-vector production
print(X.mm(Y.reshape(4, 3)))    # matrix-matrix production, typically matrix production

basic operations:
tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

torch function for maths: 
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])
tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])
tensor(66)
tensor([12, 15, 18, 21])
tensor([ 6, 22, 38])
tensor([[ 6],
        [22],
        [38]])
tensor([[ 0

In [4]:
# broadcasting

# for not same shape, tensor will copy elements to 
# extend into same shape for operations
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
c = torch.arange(8).reshape((-1, 2, 2))
print('a: \n', a)
print('b: \n',b)
print('c: \n',c)
print('a+b: \n',a+b)  # a->[[0, 0], [1, 1], [2, 2]], b->[[0, 1], [0, 1], [0, 1]]
print('b+c: \n',b+c)

a: 
 tensor([[0],
        [1],
        [2]])
b: 
 tensor([[0, 1]])
c: 
 tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
a+b: 
 tensor([[0, 1],
        [1, 2],
        [2, 3]])
b+c: 
 tensor([[[0, 2],
         [2, 4]],

        [[4, 6],
         [6, 8]]])


In [5]:
# index and slice

# index
print('index:')
print(X[-1])      # access elements by actual index, -1 means the last element index
print(X[1:3])     # access slice of tensor by :

# assign
print('\nassign:')
X[1, 2] = 9       # assign single element by precise index
Y[0:2, :] = 12    # assign multiple elements by slice :
print(X)
print(Y)

index:
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

assign:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 4.,  3.,  2.,  1.]])


In [6]:
# memory cost reduction

# use slice to keep operation and object local
Z = torch.zeros_like(Y)  # use 'zeros_like' or 'ones_like' to create same shape tensor
print('id(Z): ', id(Z))
Z[:] = X + Y
print('id(Z): ', id(Z))

# operate object on itself by +=, -=, *=, etc.
id_before = id(X)
X += Y
id_now = id(X)
print(id_before == id_now)

id(Z):  2625830886816
id(Z):  2625830886816
True


In [7]:
# transform type

# numpy to torch
A = X.numpy()
B = torch.tensor(A)
print(type(A),type(B))

# torch to others
a = torch.tensor([3.5])
print(type(a), type(a.item()))  # .item function to access scalar element

<class 'numpy.ndarray'> <class 'torch.Tensor'>
<class 'torch.Tensor'> <class 'float'>
