In [5]:
# different device
import torch
from torch import nn

# find GPU device number
print(torch.cuda.device_count())

# device type
print(torch.device('cpu'))
print(torch.device('cuda'))
print(torch.device('cuda:0'))

# define a function to try to use GPU otherwise CPU
def get_GPU(index=0):
    if torch.cuda.device_count() >= index + 1:
        return torch.device(f'cuda:{index}')
    else:
        return torch.device('cpu')

1
cpu
cuda
cuda:0


In [14]:
# store and operate tensor on GPU
x = torch.tensor([1, 2, 3])
print(x.device)

X = torch.zeros(2, 3, device=get_GPU())
print(X.device)

# copy data between different device
Z = x.cuda(0)         # copy operation: from cpu to gpu
print(x)
print(Z)
print(Z + X)
print(Z.cuda() is Z)  # if tensor is in that device, 
                      # copy operation wont create or copy a new tensor

cpu
cuda:0
tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
True
